LogLevel proxy:debug proxy_http:debug

SSLProxyEngine On
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off

ProxyPass /zabbix/ https://cml39090.danmaid.com/zabbix/
ProxyPassReverse /zabbix/ https://cml39090.danmaid.com/zabbix/

ProxyPass /dataservice/ https://manager.sdwan.danmaid.com/dataservice/
ProxyPassReverse /dataservice/ https://manager.sdwan.danmaid.com/dataservice/
ProxyPass /dataservice/login https://manager.sdwan.danmaid.com/login
ProxyPassReverse /dataservice/login https://manager.sdwan.danmaid.com/login

ProxyPass /dna/ https://cml29090.danmaid.com/dna/
ProxyPassReverse /dna/ https://cml29090.danmaid.com/dna/
