# Apache httpd configuration for Dynamic Proxy (HTTPS)
# This file can be edited manually by administrators
# Changes will be read on next application startup or reload
# NOTE: Update SSLCertificateFile/Key if needed.

<VirtualHost *:8443>
    ServerName catc.danmaid
    
    SSLEngine on
    SSLCertificateFile /etc/httpd/tls/catc.danmaid.crt
    SSLCertificateKeyFile /etc/httpd/tls/catc.danmaid.key
    
    # HTTPSバックエンド対応
    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyProtocol all -SSLv3
    
    # CSP override for iframe integration
    <Location />
        Header unset X-Frame-Options
        Header unset Content-Security-Policy
        Header set Content-Security-Policy "default-src 'self' blob: data: http://*.cisco.com https://*.cisco.com https://*.tesseractinternal.com https://s3.walkmeusercontent.com https://*.tiles.mapbox.com https://api.mapbox.com https://events.mapbox.com https://ec.walkme.com https://*.walkme.com https://*.cloudfront.net https://pendo-static-5942925331398656.storage.googleapis.com:* http://*.pendo.io:* https://*.pendo.io:* http://localhost:* https://localhost:* https://youtube.com https://www.youtube.com/ http://10.126.218.238/*; style-src 'self' blob: 'unsafe-inline' http://*.cisco.com https://*.cisco.com; script-src 'self' blob: 'unsafe-inline' http://*.cisco.com https://*.cisco.com https://*.tesseractinternal.com https://s3.walkmeusercontent.com https://*.tiles.mapbox.com https://api.mapbox.com https://events.mapbox.com https://ec.walkme.com https://*.walkme.com https://*.cloudfront.net https://pendo-static-5942925331398656.storage.googleapis.com:* http://*.pendo.io:* https://*.pendo.io:* http://localhost:* https://localhost:* https://youtube.com https://www.youtube.com/ http://10.126.218.238/* 'nonce-efa0da53-383f-49d3-9a76-0b9ba97af22a'; form-action 'self'; object-src 'none'; frame-ancestors 'self' https://localhost:8443"
    </Location>
    
    ProxyPreserveHost Off
    ProxyPass / https://192.168.1.211// disablereuse=on
    ProxyPassReverse / https://192.168.1.211//
    
    ErrorLog /var/log/httpd/catc_danmaid_error.log
    CustomLog /var/log/httpd/catc_danmaid_access.log combined
</VirtualHost>

