
# Zabbix monitoring system php web frontend

ProxyPass /zabbix http://zabbix-web:8080/zabbix
ProxyPassReverse /zabbix http://zabbix-web:8080/zabbix
ProxyTimeout 300

# リバースプロキシでZabbix Web UIへ転送
<Proxy "http://zabbix-web:8080/zabbix">
    Allow from all
</Proxy>

# 必要に応じてアクセス制御やDirectory設定を追加
